### ISSUE TITLE
Make Data Store Seek Less

### ISSUE THREAD

**Issue by waldheinz** [freenet/fred#210]
There was some discussion on IRC yesterday about some potential improvements for the (salted hash) data store I suggested. I'd like to have this issue here attract some discussion and track the progress (if any).

The initial idea was to reduce the number of seeks (on rotating media) needed to perform the store's duties. There are two things I brought up:

  * First, I'd like to store the headers in a single file together with the payload data. Currently, this data is kept in two [separate files][1]. This already cuts the number of seeks half for the usual "get some data from the store" case. I assume this is the usual case, because the bloom filters prevent false positives with great success.
  * Next, I'd like to replace the [double-hashing scheme][2] used to probe for candidate slots when reading/writing with linear probing. This would eliminate the need for seeks here as well. There are also concerns about the function used for the double-hashing: `h + 141 i^2 + 13 i` -- the quality of this function is unknown, but voice has been raised that `141` is not prime, but maybe there should be a prime used in this place. My maths is too weak to figure that out.

To keep things simple, above would only be used for new nodes. Existing data stores are not converted. 

[1]: https://github.com/freenet/fred-staging/blob/next/src/freenet/store/saltedhash/SaltedHashFreenetStore.java#L562
[2]: https://github.com/freenet/fred-staging/blob/next/src/freenet/store/saltedhash/SaltedHashFreenetStore.java#L2090

**Comment by xor-freenet** [comment]
We do not use this bugtracker.
The proper bugtracker is at: https://bugs.freenetproject.org

Can you please migrate this issue to that one on your own? If not, feel free to tell me, then I can take care of it.
