### ISSUE TITLE
I DID SUBSCRIBE, HENCE LOGIN WITH USER NAME AND PASSWORD DUH!      FREENET ISSUE GUY AGAIN

### ISSUE THREAD

**Issue by thisguy0417** [freenet/fred#366]
I DID SUBSCRIBE , I DID THE FREE THING,  I GAVE MY EMAIL ADDY BUT I NEVER GOT A VERIFICATION EMAIL AND I REPEATEDLY SENT THE VERIFICATION MESSAGE FROM HERE BUT NVR GOT IT  CHECK YOUR SYSTEM, I FILLED OUT THE SUBSCRIPTION , MADE MY USERNAME AND PASSWORD I DONT UNDERSTAND WHY YOURE SAYING I NEED TO SUBSCRIBE,BUT,
 IM GLAD SOMEONE REPLIED, HOWEVER ALL THE PLACES YOU TOLD ME TO CONTACT ARE NOT THERE OR HAVE STUFF THAT DOESNT HELP THATS WHY I CAME HERE IT SAYS OPEN ISSUE WITH FREENET SO THATS WHAT IM DOING I NEEEEEEEED HHHHHEEELLLPPP WITH THIS , IF I LEFT THE ADVANCED SETTINGS AT DEFAULT, AND I HAVE, I WOULD GET 10 OR 12 PEERS, WHT CANT JUST TELL ME HOW EXACTLY TO SET IT UP FOR MAX PREFORMANCE AND USEABILITY WHEN I GIVE DETAILS OF MY MACHINE AND THE ISSUES IM HAVING THEY WANT PEOPLE TO USE THEIR PRODUCT THEY SHOULD HAVE EASY ACCESS TO HELP ANS SUPPORT, I WANT TO BE ON ANT GET THINGS BUT CANT KEEP IT GOING LONG ENOUGH ,BY THE WAY I HAVE NO DISK ERRORS  OR VIRII OR MALWARE OR ROOTKITS MY MACHINE IS CLEAN BASICALLY NEW BUT......... 
SO IF I CANT GET REAL HELP HERE, ON FREENET FREDS THING ITS REDICULAS THAT ITS IMPOSSIBLE TO FIND UP TO DATE(2015) HELP AND SUPPORT, AND IF THRERS ONLY 300000 PEERS ON WORLDWIDE GETTING OUT HELP AND SUPPORT INFO SHOULDNT BE THAT HARD I KNOW THAT NUMBER IS PROB LOW BUT THE POINT IS ITS NOT GOOGLE ANT THERE ISNT 4.5BILLION PEOPLE USING IT, HOWEVER ON GOOGLE IF ONE HAS AN ISSUE CONTACTING GOOGLE FOR SUPPORT IS EASY , THE CREATORS OF FREENET SHOULD HAVE INCORPORATED THAT IN THE PROJECT INCLUDING SETUP ANT INSTALLATION ALONG WITH A BASIC TO PRO CONFIGURATION GUIDE SO EVERYONE CAN ENJOY THE WONDERFUL WORLD OF THE INNERINTERNET  SORRY NOT EVERYONE IS A COMPUTER GEEK BUT I JUST FOLLOWED WHAT THE SETTINGS TELL ME THE ONLY THINGS I CHANGED WAS THE AMOUNT OF RAM CACHE AND THE DATASTORE SIZES THEY SAYIF ITS BIGGER THAN AN UNSTATED AMOUNT THAT IT WILL BE STORED TO THE DISK AGAIN I HAVE PLENTY OF ROOM AND SPEED I JUST NEED TO KNOW HOW TO SET IT UP SO I CAN BE ON (AS FREENET WANTS US TO BE) 24/7 BUT IF ONE CANT KEEP IT RUNNING, HAS LOOKED FOR HELP EVERYWHER ONLY TO FIND STUFF FROM 4 AND 5 YEARS AGO EVEN THOUGH IN MY QUERY I PUT IN 2015 PLEASE DONT BLOW ME OFF AGAIN GITHUB AND FREENET HAVE CONNECTIONS SO I KNOW THIS COULD BE FORWARDED TO SOMEONE THAT HAS SOMETHING TO DO WITH FREENET  I DID SUBSCRIBE PLEASE HELP...........                                          

                                                                                SINCERLY THISGUY0417
  
 PS AFEW THINGS, IF I DIDNT SUBSCRIBE , HOW DID I LOG IN WITH MY USERNAME AND PASSWORD, I WOULDNT HAVE BEEN ABLE TO WRITE THIS,
 I WROTE THIS BIG SO MAYBE YOU UNDERSTAND IT BETTER, NOT YELLING BUT I AM PISSED SEEMS LIKE THIS PROGRAM IS A FRAUD WITH THE LACK OF ANY KIND OF HELP AND SUPPORT IM NOT MESSING AROUND THERE IS NO HELP OUT THERE FOR FREENET IN 2015, MAYBE IF I LEARNED ABOUT THIS YEARS AGO I WOULDNT BE HERE SERIOUSLY ASKING FOR HELP
I DIDNT MESS WITH ANYTHING OTHER THAN WHAT I STATED ABOVE IN THE CONFIGURATION SETTINGS I JUST NEED HELP DONT SEND ME TO THOSE USELESS OLD OR NO HELPFUL INFO I DID THE MAILING LIST THING 2 WEEKS AGO BEEN ON THE IRC THING THE FAQ IS FROM 09 ALL THE WIKI HELP IS OLD OR GONE, IVE LOOKED EVERYWHERE PPPPPPLLLLLEEEEEAAAAASSSSSEEEE HHHHEEEELLLLPPPP!!!!

**Comment by Thynix** [comment]
Please don't shout at us.

**Comment by Thynix** [comment]
Closed like #365.
